version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
branches:
  only:
    - master
    - development
  except:
    - gh-pages
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - gradlew.bat --version
build_script:
  - gradlew.bat -u -i clean assemble
test_script:
  - gradlew.bat -u -i -S check
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
on_failure:
  - echo Somebody setup us the bomb
